using BusBooking.API.DTOs.Booking;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace BusBooking.API.Helpers;

public static class TicketPdfGenerator
{
    public static byte[] Generate(BookingResponseDto booking)
    {
        return Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(36);
                page.DefaultTextStyle(text => text.FontSize(11));

                page.Header()
                    .Text($"Bus Ticket - {booking.BookingRef}")
                    .SemiBold()
                    .FontSize(22)
                    .FontColor(Colors.Red.Medium);

                page.Content().PaddingVertical(20).Column(column =>
                {
                    column.Spacing(14);

                    column.Item().Border(1).BorderColor(Colors.Grey.Lighten2).Padding(12).Column(card =>
                    {
                        card.Spacing(8);
                        card.Item().Text($"{booking.Trip?.Source} to {booking.Trip?.Destination}").SemiBold().FontSize(18);
                        card.Item().Text($"Bus: {booking.Trip?.BusName} ({booking.Trip?.BusType})");
                        card.Item().Text($"Departure: {booking.Trip?.DepartureTime:dd MMM yyyy, hh:mm tt}");
                        card.Item().Text($"Arrival: {booking.Trip?.ArrivalTime:dd MMM yyyy, hh:mm tt}");
                        card.Item().Text($"Status: {booking.Status.ToUpperInvariant()}");
                    });

                    column.Item().Text("Passengers").SemiBold().FontSize(14);
                    column.Item().Table(table =>
                    {
                        table.ColumnsDefinition(columns =>
                        {
                            columns.RelativeColumn(3);
                            columns.RelativeColumn();
                            columns.RelativeColumn();
                            columns.RelativeColumn();
                        });

                        table.Header(header =>
                        {
                            header.Cell().Element(HeaderCell).Text("Name");
                            header.Cell().Element(HeaderCell).Text("Age");
                            header.Cell().Element(HeaderCell).Text("Gender");
                            header.Cell().Element(HeaderCell).Text("Seat");
                        });

                        foreach (var passenger in booking.Passengers)
                        {
                            table.Cell().Element(BodyCell).Text(passenger.Name);
                            table.Cell().Element(BodyCell).Text(passenger.Age.ToString());
                            table.Cell().Element(BodyCell).Text(passenger.Gender);
                            table.Cell().Element(BodyCell).Text(passenger.SeatNumber);
                        }
                    });

                    column.Item().AlignRight().Text($"Total Fare: Rs. {booking.TotalFare:N2}").SemiBold().FontSize(14);
                    column.Item().Text("Please carry a valid photo ID during travel. Reach the boarding point at least 15 minutes before departure.")
                        .FontColor(Colors.Grey.Darken2);
                });

                page.Footer().AlignCenter().Text(text =>
                {
                    text.Span("Generated by BusReserve on ");
                    text.Span(DateTime.UtcNow.ToString("dd MMM yyyy, hh:mm tt"));
                });
            });
        }).GeneratePdf();
    }

    private static IContainer HeaderCell(IContainer container)
    {
        return container.DefaultTextStyle(text => text.SemiBold())
            .Background(Colors.Grey.Lighten3)
            .Padding(6);
    }

    private static IContainer BodyCell(IContainer container)
    {
        return container.BorderBottom(1)
            .BorderColor(Colors.Grey.Lighten3)
            .Padding(6);
    }
}
